project/BlogPost/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired

class BlogPostForm(FlaskForm):
    title  = StringField('Title', validators=[DataRequired()])
    text   = TextAreaField('Text', validators=[DataRequired()])
    submit = SubmitField('Post')

project/survey/forms.py
from flask_wtf import FlaskForm
from wtforms import IntegerField, SubmitField, StringField
from wtforms.validators import DataRequired

class SurveyForm(FlaskForm):
    age            = IntegerField('How old are you?', validators=[DataRequired()])
    gender         = IntegerField('What is your gender? Type 1 for Male and 2 for Female 3 for Other', validators=[DataRequired()])
    height         = IntegerField('How tall are you in inches?', validators=[DataRequired()])
    start_weight   = IntegerField('How much did you weigh in pounds at start of Whole 30?', validators=[DataRequired()])
    end_weight     = IntegerField('How much did you weigh in pounds at end of Whole 30?', validators=[DataRequired()])
    experience     = StringField('Please describe the Whole 30 exeperience for you.', validators=[DataRequired()])
    submit         = SubmitField('Submit Survey')

project/BlogPost/views.py
from flask import render_template, url_for, flash, request, redirect, Blueprint
from  flask_login import current_user, login_required
from project import db
from project.models import BlogPost
from project.BlogPost.forms import BlogPostForm

blog_posts = Blueprint('blog_posts', __name__)

#  Create POST

@blog_posts.route('/create',methods=['GET','POST'])
@login_required
def create_post():
    form = BlogPostForm()

    if form.validate_on_submit():

        blog_post = BlogPost(title=form.title.data,
                             text=form.text.data,
                             user_id=current_user.id
                             )
        db.session.add(blog_post)
        db.session.commit()
        flash("Blog Post Created")
        return redirect(url_for('core.index'))

    return render_template('create_post.html',form=form)



# Blog Post view

@blog_posts.route('/<int:blog_post_id>')
def blog_post(blog_post_id):
    blog_post=BlogPost.query.get_or_404(blog_post_id)
    return render_template('blog_post.html',title=blog_post.title,
                            date=blog_post.date,post=blog_post
    )
# Update Blog Post
@blog_posts.route("/<int:blog_post_id>/update", methods=['GET', 'POST'])
@login_required
def update(blog_post_id):
    blog_post = BlogPost.query.get_or_404(blog_post_id)
    if blog_post.author != current_user:
        # Forbidden, No Access
        abort(403)

    form = BlogPostForm()
    if form.validate_on_submit():
        blog_post.title = form.title.data
        blog_post.text = form.text.data
        db.session.commit()
        flash('Post Updated')
        return redirect(url_for('blog_posts.blog_post', blog_post_id=blog_post.id))
    # Pass back the old blog post information so they can start again with
    # the old text and title.
    elif request.method == 'GET':
        form.title.data = blog_post.title
        form.text.data = blog_post.text
    return render_template('create_post.html', title='Update',
                           form=form)

# delete a blog post
@blog_posts.route('/<int:blog_post_id>/delete', methods=['GET','POST'])
@login_required
def delete_post(blog_post_id):

    blog_post = BlogPost.query.get_or_404(blog_post_id)
    if blog_post.author != current_user:
        abort(403)

    db.session.delete(blog_post)
    db.session.commit()
    flash('Blog Post Deleted')
    return redirect(url_for('core.index'))

project/core/views.py
# core/views.def

from flask import render_template,request,Blueprint

from project.models import BlogPost

core = Blueprint('core',__name__)

@core.route('/')
def index():
    page = request.args.get('page', 1, type=int)
    blog_posts = BlogPost.query.order_by(BlogPost.date.desc()).paginate(page=page, per_page=6)
    return render_template('index.html',blog_posts=blog_posts)

@core.route('/info')
def info():
    return render_template('info.html')

project/survey/views.py
from flask import render_template, url_for, flash, request, redirect, Blueprint
from  flask_login import current_user, login_required
from project import db
from project.models import Survey
from project.survey.forms import SurveyForm

survey = Blueprint('survey', __name__)

@survey.route('/survey',methods=['GET','POST'])
@login_required
def complete_survey():
    form = SurveyForm()

    if form.validate_on_submit():

        survey = Survey(age            =form.age.data,
                        gender         =form.gender.data,
                        height         =form.height.data,
                        start_weight   =form.start_weight.data,
                        end_weight     =form.end_weight.data,
                        experience     =form.experience.data,
                        user_id        =current_user.id
                        )
        db.session.add(survey)
        db.session.commit()
        flash("Thanks for completing the survey")
        return redirect(url_for('core.index'))


    return render_template('survey.html',form=form)

project/users/views.py
#users/views.py
from flask import render_template, url_for, redirect,request, Blueprint, flash
from flask_login import login_user, current_user, logout_user, login_required
from werkzeug.security import generate_password_hash,check_password_hash
from project import db
from project.models import User, BlogPost
from project.users.forms import RegistrationForm, LoginForm, UpdateUserForm
from project.users.picture_handler import add_profile_pic

users = Blueprint('users',__name__)

# register
@users.route('/register',methods=['GET','POST'])
def register():
    form = RegistrationForm()

    if form.validate_on_submit():
        user = User(email=form.email.data,
                    username=form.username.data,
                    password=form.password.data)

        db.session.add(user)
        db.session.commit()
        flash('Thanks for registration!')
        return redirect(url_for('users.login'))

    return render_template('register.html',form=form)

    #if the login is not valid send them back to registration page
    return render_template(url_for('register.html', form=form))
# login
@users.route('/login', methods=['GET','POST'])
def login():

    form = LoginForm()
    if form.validate_on_submit():
        # Grab the user from our User Models table
        user = User.query.filter_by(email=form.email.data).first()

        ## I had this in one line with an and statement, but kept throwing and error
        ## It is possible that parenthesis were necessary could change back    
        if user is not None:
            if user.check_password(form.password.data):

                login_user(user)
                flash('Log in Success!')

                next = request.args.get('next')

                if next == None or not next[0]=='/':
                    next = url_for('core.index')

                    return redirect(next)

    return render_template('login.html', form=form)

# logout
@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("core.index"))

# account (update user info)
@users.route('/account', methods=['GET','POST'])
@login_required
def account():

    form = UpdateUserForm()
    if form.validate_on_submit():

        if form.picture.data:
            username = current_user.username
            pic = add_profile_pic(form.picture.data,username)
            current_user.profile_image = pic

        current_user.username = form.username.data
        current_user.email =form.email.data
        db.session.commit()
        flash('User Account Updated')
        return redirect(url_for('users.account'))

    elif request.method =="GET":
        form.username.data = current_user.username
        form.email.data = current_user.email

    profile_image = url_for('static', filename='profile_pics/'+current_user.profile_image)
    return render_template('account.html', profile_image= profile_image, form = form)

# user list of blog posts
@users.route("/<username>")
def user_posts(username):
    page = request.args.get('page',1,type=int)
    user = User.query.filter_by(username=username).first_or_404()
    blog_posts = BlogPost.query.filter_by(author=user).order_by(BlogPost.date.desc()).paginate(page=page,per_page=5)
    return render_template('user_blog_posts.html',blog_posts=blog_posts,user=user)


# survey

project/templates/account.html
{% extends "base.html" %}
{% block content %}

<div class="jumbotron">
  <div align='center'>
    <h1 >Welcome to the page for {{current_user.username}}</h1>
    <img align='center' src="{{ url_for('static', filename='profile_pics/' + current_user.profile_image)}}">
    <p>{{ current_user.email }}</p>
  </div>
</div>
<div class="container">
  <form  method="POST" action="" enctype="multipart/form-data">
    {{ form.hidden_tag() }}
    <div class="form-group">
      {{ form.username.label(class="form-group") }}
      {{form.username(class='form-control')  }}
    </div
    <div class="form-group">
      {{ form.email.label(class="form-group") }}
      {{form.email(class='form-control')  }}
    </div>
    <div class="form-group">
      {{ form.picture.label(class="form-group") }}
      {{ form.picture(class="form-control-file") }}
    </div>
    <div class="form-group">
        {{ form.submit(class="btn btn-primary") }}
    </div>
  </form>

</div>

{% endblock content %}

project/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <meta charset="utf-8">
    <title></title>
  </head>
  <body>

    <ul class='nav'>
      <li class='nav-link'>
        <a href="{{url_for('core.index')}}">Home</a>
      </li>
      <li class='nav-link'>
        <a href="{{url_for('core.info')}}">About</a>
      </li>
      {% if current_user.is_authenticated %}
      <li class='nav-link'>
        <a href="{{url_for('users.logout')}}">Log Out</a>
      </li>
      <li class='nav-link'>
        <a href="{{url_for('users.account')}}">Account</a>
      </li>
      <li class='nav-link'>
        <a href="{{url_for('blog_posts.create_post')}}">Create Blog Post</a>
      </li>
      <li class='nav-link'>
        <a href="{{url_for('survey.complete_survey')}}">Take Survey</a>
      </li>
    {% else %}
      <li class='nav-link'>
        <a href="{{url_for('users.login')}}">Log In</a>
      </li>
      <li class='nav-link'>
        <a href="{{url_for('users.register')}}">Register</a>
      </li>
      {% endif %}
    </ul>
<div class="container">
  {% block content %}

  {% endblock %}
</div>


  </body>
</html>

project/templates/blog_post.html
{% extends "base.html" %}
{% block content %}
<div class="jumbotron">
  <h1>{{ post.title }}</h1>
  <h2>Written by: {{post.author.username}}</h2>
  <h3>Published: {{ post.date.strftime('%B %d, %Y') }}</h3>
  <p>{{post.text}}</p>
   {% if post.author == current_user %}
     <div>
       <a class="btn btn-secondary" href="{{ url_for('blog_posts.update', blog_post_id=post.id) }}">Update</a>
       <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#del_modal">Delete</button>
     </div>
   {% endif %}
</div>




  <!-- Modal for Pop Up-->
  {# https://getbootstrap.com/docs/4.1/components/modal/ #}
  {# Notice how the link with the id to the button above! #}
  <div class="modal" tabindex="-1" role="dialog" id="del_modal">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Delete Post Pop up Modal</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <p>Are you sure you want to delete this blog post?</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>

          <form action="{{ url_for('blog_posts.delete_post', blog_post_id=post.id) }}" method="POST">
            <input class="btn btn-danger" type="submit" value="Delete">
          </form>
        </div>
      </div>
    </div>
  </div>

{% endblock content %}

project/templates/create_post.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <form class="form-group" method="POST">
     {{ form.hidden_tag() }}

     <div class="form-group">
     {{ form.title.label(class="form-control-label") }}
     {{ form.title(class="form-control form-control-lg ") }}
     </div>
     <div class="form-group">
     {{ form.text.label(class="form-control-label") }}
     {{ form.text(class="form-control form-control-lg") }}
     </div>
     <div class="form-group">
         {{ form.submit(class="btn btn-outline-info") }}
     </div>
  </form>

</div>

{% endblock content %}

project/templates/index.html
{% extends "base.html" %}
{% block content %}
  <div class="jumbotron">
    <h1>Welcome to Whole 30 Blog and Survey Site</h1>
    <br>
    <p>Welcome, this site is designed to share information on the Whole 30.  You can sign up and post your experiences about your journey through the Whole 30 or ask questions of other who participated.  Also be sure to take the survey in order to provide data about the effectiveness and results you had after the Whole 30.  This will allow for the use of machine learning to identify what are typical results of the eating plan</p>
    <br>
    <a href="{{url_for('survey.complete_survey')}}">Survey</a>
  </div>

  <div class="container">

    {# Go through each blog post #}
    {% for post in blog_posts.items %}

    <div class="card" >

      <div class="card-body">


        <h2><a class="card-title" href="  {{ url_for('blog_posts.blog_post', blog_post_id=post.id) }}">{{ post.title }}</a></h2>
        <a href="{{ url_for('users.user_posts', username=post.author.username) }}">Written By: {{ post.author.username }}</a>
        <p>Published on: {{ post.date.strftime('%Y-%m-%d') }}</p>
        <p class="card-text">{{ post.text[:100] }}...</p>
        <a href="{{ url_for('blog_posts.blog_post', blog_post_id=post.id) }}" class="btn btn-primary">Read Blog Post</a>
      </div>
    </div>

   {% endfor %}

   <nav aria-label="Page navigation example">
     <ul class="pagination justify-content-center">
       {% for page_num in blog_posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
          {% if blog_posts.page == page_num %}
          <li class="page-item disabled">
            <a class="page-link" href="{{ url_for('core.index', page=page_num) }}">{{ page_num }}</a></li>
          </li>
          {% else %}
            <li class="page-item"><a class="page-link" href="{{ url_for('core.index', page=page_num) }}">{{ page_num }}</a></li>
          {% endif %}
      {% endfor %}
    </nav>




{% endblock %}

project/templates/info.html
{% extends "base.html" %}
{% block content %}
  <div class="jumbotron">
    <h1>Data on the Whole 30</h1>
    <p>When deciding to start the Whole 30 I did what a great deal of people probably do I
    looked at some informational websites and I took into account the testimonials of others that
  had done the program.  I felt fairly confident that going through the Whole 30 would be good for 
  , at the time I was also studying some data science and I thought that maybe I could use some of the tools that
  I was learning to analyze people self reported Whole 30 results and maybe find some unique conclusions about the Whole 30.
<<br>
I was studying Flask so I decided to build a webpage that using flask that would connect to a SQL database.  I could then
attach a survey that would gather information from Whole 30 pratictioners and hopefully after getting some responses I will be able
to conduct some machine learning to make predictions about what to expect on the whole 30.  I also wanted to get some written observations
to practice some Natural Language Processing.
<br>
Currently, the website does not nave a great user feel as I was concerned mostly with the backend.  In the future I hope to make the
website more user friendly as well as add a dashboard to summarize results generated from the database.  Right now you have to be a member to take the survey,
but you do not have to provide a valid email to register.  All that is required is that the email has the @ sign and is unique.
</p>
  </div>
{% endblock %}

project/templates/login.html
{% extends "base.html" %}
{% block content %}


  <form  method="POST">
    {{form.hidden_tag()}}
    {{form.email.label}}{{form.email}}<br>
    {{form.password.label}}{{form.password}}<br>
    {{form.submit()}}
  </form>

  {% endblock %}

project/templates/register.html
{% extends "base.html" %}
{% block content %}


  <form  method="POST">

    <div class="form group">

    </div>
    {{form.hidden_tag()}}

    <div class="form group">
    {{form.email.label(class='form-group')}}{{form.email}}<br>
    </div>

    <div class="form group">
    {{form.username.label(class='form-group')}}{{form.username}}<br>
    </div>

    <div class="form group">
    {{form.password.label(class='form-group')}}{{form.password}}<br>
    </div>

    <div class="form group">
    {{form.pass_confirm.label(class='form-group')}}{{form.pass_confirm}}<br>
    </div>

    {{form.submit()}}
  </form>

{% endblock %}

project/templates/survey.html
{% extends "base.html" %}
{% block content %}
<br>
<br>
<h1>Welcome {{current_user.username}} thanks for taking our survey</h1>
<br>
<br>
<div class="form-group">


  <form  method="POST">
    {{form.hidden_tag()}}
    {{form.age.label(class='form-group')}}{{form.age}}<br>
    {{form.gender.label(class='form-group')}}{{form.gender}}<br>
    {{form.height.label(class='form-group')}}{{form.height}}<br>
    {{form.start_weight.label(class='form-group')}}{{form.start_weight}}<br>
    {{form.end_weight.label(class='form-group')}}{{form.end_weight}}<br>
    {{form.experience.label(class='form-group')}}
    {{form.experience(class='form-control form-control-lg')}}<br>
    {{form.submit()}}

  </form>
</div>



{% endblock content %}

project/templates/user_blog_posts.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <div class="jumbotron">
    <div align='center'>
      <h1 >Welcome to the page for {{user.username}}</h1>
      <img align='center' src="{{ url_for('static', filename='profile_pics/' + user.profile_image) }}">
    </div>
  </div>

  {% for post in blog_posts.items %}

            <h2><a href="{{ url_for('blog_posts.blog_post', blog_post_id=post.id) }}">{{ post.title }}</a></h2>
            Written by: <a href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
            <p class="text-muted">Published on: {{ post.date.strftime('%Y-%m-%d') }}</p>
            <br>
              <p>{{post.text}}</p>
            <br>

  {% endfor %}


  </div>

  <nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
      {# http://flask.pocoo.org/snippets/44/ #}

      {% for page_num in blog_posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
              {% if blog_posts.page == page_num %}
                <li class="page-item disabled">
                  <a class="page-link" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a></li>
                </li>
              {% else %}
                <li class="page-item"><a class="page-link" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a></li>
              {% endif %}
      {% endfor %}
  </nav>
  {% endblock content %}